var modules={
    module1:{
        instructionalcontent: "<p>During this study you will be interacting with simulated **client** (not another human). What the client writes is generated by a computer program. Your role is to act as their **therapist** and to practice your listening skills while you do it.</p><p>By listening skills we mean something very specific. Your goal is to try and non-judgmentally listen to your client using two key skills: **open questions**  and **reflections**.</p><p>An **open question** is a question that cannot be answered with a simple yes or no answer. The goal is to elicit a longer response and allow the listener to express his or her feelings. For example, 'how are you feeling today?' is a good example of an open question.</p><p>A **reflection** is a way of communicating to your client that you are trying to understand by repeating back a version what you think they have been saying. It is important to avoid including any judgment, confrontation or advising in what you say to the client. For example, 'it sounds like you're having a hard time at work' would be a reflection if the client was talking about problems at work. A reflection lets your client understand that you are listening non-judgmentally.</p>",
        therapistpic: "assets/avatar8.png",
        therapisttalkturn1: "",
        clientpic: "assets/avatar7.png",
        clienttalkturn1: "I want to be alone, but not lonely. I want friends but hate socializing. Want success, but have no desire to be productive. I’m lost in my own conscience.",
        problemdescription: "Practice how to apply these skills while having a conversation with a client.",
        probleminstruction: "Write a response to the client as the therapist:",
        problemtimevalue: "45",
        feedbackcontent: "'Every desire has a competing desire; you must feel stuck' and 'You’re in a lose-lose situation' are both reflections. 'Every desire has a competing desire; you must feel stuck' has the added benefit of reflecting a previously unspoken emotion. 'How does that feel?' is an open question. 'I’ve been there' is statement about the therapist.",
        hintcontent: "<div class='alert alert-primary' role='alert'>Perhaps at this turn in the conversation you might try to reflect what the client said.</div>",
        validationcontent: "<div class='alert alert-warning' role='alert'>Please select a response to client before moving on to the next step.</div>",
        readycountdown: "3",
        inputformat: "multichoice4items",
        turn1item1: "Every desire has a competing desire; you must feel stuck.",
        turn1item2: "You’re in a lose-lose situation.",
        turn1item3: "How does that feel?",
        turn1item4: "I’ve been there.",
        correctanswerturn1: "item1selected",
        correctanswerturn2: "item2selected"
    }/*,
    module2:{
        instructionalcontent: "<p>Ethnic and cultural differences must be considered when expressing empathy because they influence how both you and your client interpret verbal and nonverbal communications.</p>",
        therapistpic: "assets/avatar8.png",
        therapisttalkturn1: "",
        clientpic: "assets/avatar7.png",
        clienttalkturn1: "I'm feeling kind of blue. I'm feeling anxious at work.",
        problemdescription: "Practice how to reflect client statements",
        probleminstruction: "Reflect the client statement:",
        problemtimevalue: "45",
        feedbackcontent: "Keep going, MI is all about reflections. Reflect those client statements!",
        hintcontent: "<div class='alert alert-primary' role='alert'>Start to reflect client statements by paraphrasing what the client said.</div>",
        readycountdown: "3"
    }*/
}